### using this dataset:

In [5]:

import matplotlib.pyplot as plt
import netCDF4 as nc
from netCDF4 import Dataset
import numpy as np
import pandas as pd
import xarray as xr
import os

In [6]:
zac_path = 'C:/Users/zseal/OneDrive/Documents/GitHub/ISAT420_Semester_Project/'
sal_path = 'Salinity_Data/Atlas.nc'
full_path =( f'{zac_path}{sal_path}')
#print(full_path)
full_df = xr.open_dataset(full_path)

In [8]:
sal_df=full_df["timeseries_salinity"]
print(sal_df)

<xarray.DataArray 'timeseries_salinity' (three: 3, timeseries_time: 14609)> Size: 175kB
[43827 values with dtype=float32]
Coordinates:
  * timeseries_time  (timeseries_time) datetime64[ns] 117kB 1985-01-01T12:00:...
Dimensions without coordinates: three
Attributes:
    long_name:  Practical salinity timeseries
    units:      PSS-78
    time:       timeseries_time
    structure:  Bay-wide average (excluding the continental shelf) of... Colu...

In [9]:
sal_df.head(20)

<xarray.DataArray 'timeseries_salinity' (three: 3, timeseries_time: 20)> Size: 240B
[60 values with dtype=float32]
Coordinates:
  * timeseries_time  (timeseries_time) datetime64[ns] 160B 1985-01-01T12:00:0...
Dimensions without coordinates: three
Attributes:
    long_name:  Practical salinity timeseries
    units:      PSS-78
    time:       timeseries_time
    structure:  Bay-wide average (excluding the continental shelf) of... Colu...

In [10]:
sal_df.tail(20)

<xarray.DataArray 'timeseries_salinity' (three: 3, timeseries_time: 20)> Size: 240B
[60 values with dtype=float32]
Coordinates:
  * timeseries_time  (timeseries_time) datetime64[ns] 160B 2024-12-11T12:00:0...
Dimensions without coordinates: three
Attributes:
    long_name:  Practical salinity timeseries
    units:      PSS-78
    time:       timeseries_time
    structure:  Bay-wide average (excluding the continental shelf) of... Colu...

In [11]:
#sal_df_sal=sal_df['1985-01-09 12:00:00']
sal_df.sel(timeseries_time="1985-01-09")

<xarray.DataArray 'timeseries_salinity' (three: 3, timeseries_time: 1)> Size: 12B
[3 values with dtype=float32]
Coordinates:
  * timeseries_time  (timeseries_time) datetime64[ns] 8B 1985-01-09T12:00:00
Dimensions without coordinates: three
Attributes:
    long_name:  Practical salinity timeseries
    units:      PSS-78
    time:       timeseries_time
    structure:  Bay-wide average (excluding the continental shelf) of... Colu...

In [19]:
#full_df.variables.keys()
#(print(full_df.variables))
print(full_df["timeseries_salinity"].shape)
print(full_df["timeseries_salinity"].dims)
print(full_df["timeseries_salinity"]["three"].values)

(3, 14609)
('three', 'timeseries_time')
[0 1 2]

timeseries_salinity
wqmp_salinity
salinity_bottom
salinity_surface
latitude
longitude
timeseries_time

In [14]:
cols = [
    "timeseries_time",
    "latitude",
    "longitude",
    "timeseries_salinity",
    "wqmp_salinity",
    "salinity_bottom",
    "salinity_surface"
]

df_salinity = full_df[cols]

In [15]:
df_salinity.head()

<xarray.Dataset> Size: 1kB
Dimensions:              (timeseries_time: 5, latitude: 5, longitude: 5,
                          three: 3, five: 5, n_wqmp_salinity: 5, time: 5)
Coordinates:
  * timeseries_time      (timeseries_time) datetime64[ns] 40B 1985-01-01T12:0...
  * latitude             (latitude) float64 40B 36.55 36.56 36.56 36.57 36.57
  * longitude            (longitude) float64 40B -77.4 -77.39 ... -77.38 -77.37
  * time                 (time) datetime64[ns] 40B 2001-01-16 ... 2001-05-18
Dimensions without coordinates: three, five, n_wqmp_salinity
Data variables:
    timeseries_salinity  (three, timeseries_time) float32 60B ...
    wqmp_salinity        (five, n_wqmp_salinity) float32 100B ...
    salinity_bottom      (time, latitude, longitude) float32 500B ...
    salinity_surface     (time, latitude, longitude) float32 500B ...
Attributes:
    history:          Atlas of hydrodynamical and biogeochemical conditions i...
    Description:      Atlas of modeled hydrodynamical/biogeochemical conditio...
    Citation:         St-Laurent, P., M.A.M.Friedrichs, An atlas for physical...
    Author:           St-Laurent et al. (person of contact: pst-laurent@vims....
    Acknowledgments:  This work was supported by the National Science Foundat...
    Created:          29-Dec-2025 12:21:15
    Conventions:      CF-1.6

In [37]:

surface_salinity = full_df["timeseries_salinity"].isel(three=0)
time_df = surface_salinity.to_dataframe().reset_index()
#time_df.to_csv("salinity_timeseries_dataset.csv", index=False)

mean_surface = full_df["salinity_surface"].mean(dim="time")
spatial_df = mean_surface.to_dataframe().reset_index()
#spatial_df.to_csv("salinity_spatial_timeseries_dataset.csv", index=False)

In [38]:
time_df.head()

      timeseries_time  timeseries_salinity
0 1985-01-01 12:00:00            15.552751
1 1985-01-02 12:00:00            15.651566
2 1985-01-03 12:00:00            15.420301
3 1985-01-04 12:00:00            15.700674
4 1985-01-05 12:00:00            15.585882

In [39]:
spatial_df.head()

   latitude  longitude  salinity_surface
0   36.5526  -77.40144               NaN
1   36.5526  -77.39460               NaN
2   36.5526  -77.38776               NaN
3   36.5526  -77.38092               NaN
4   36.5526  -77.37408               NaN

In [30]:
spatial_df['salinity_surface'].isna().count()

np.int64(197316)

In [29]:
spatial_df['salinity_surface'].count()

np.int64(60410)